name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOEKN_FOREVER_FULL_WRITE }}
    - name: Add date to打卡.md
      run: |
        echo "$(date): Check-in
        " >> 打卡.md
    - name: Commit changes
      run: |
        git config --global user.name "Soltus"
        git config --global user.email "liaoshanyi@qq.com"
        git add 打卡.md
        git commit -m "Add daily check-in"
    - name: Push changes
      run: |
        git push https://Soltus:${{ secrets.TOEKN_FOREVER_FULL_WRITE }}@github.com/Soltus/Soltus.git
