name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add date to打卡.md
      run: |
        echo "$(date): Check-in" >> 打卡.md
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add 打卡.md
        git commit -m "Add daily check-in"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
